import React, { useState } from 'react';
import { 
  X, 
  Upload, 
  FileText, 
  Sparkles, 
  CheckCircle2, 
  AlertCircle, 
  ArrowRight, 
  Briefcase, 
  GraduationCap, 
  TrendingUp, 
  DollarSign, 
  BookOpen, 
  Star, 
  Download, 
  Copy, 
  Check, 
  ExternalLink, 
  Layers, 
  Brain,
  ShieldCheck,
  RefreshCw,
  Search,
  ChevronRight
} from 'lucide-react';
import { SAMPLE_RESUMES, SampleResume, CareerRoleOpportunity, CourseSuggestion } from '../../data/resumeData';
import { parseResumeText, ParsedResumeResult } from '../../utils/resumeParser';

interface ResumeScannerModalProps {
  isOpen: boolean;
  onClose: () => void;
  onOpenRoadmap?: () => void;
}

export const ResumeScannerModal: React.FC<ResumeScannerModalProps> = ({ 
  isOpen, 
  onClose,
  onOpenRoadmap 
}) => {
  const [inputText, setInputText] = useState('');
  const [fileName, setFileName] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisStep, setAnalysisStep] = useState(0);
  const [results, setResults] = useState<ParsedResumeResult | null>(null);
  const [activeTab, setActiveTab] = useState<'opportunities' | 'courses' | 'ats'>('opportunities');
  const [copiedKeywords, setCopiedKeywords] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);
  const [selectedRoleIndex, setSelectedRoleIndex] = useState(0);

  if (!isOpen) return null;

  const analysisSteps = [
    'Ingesting document & parsing structural text blocks...',
    'Extracting technical competencies, tools & leadership history...',
    'Calibrating neural match scores across 12,000+ live market roles...',
    'Synthesizing personalized course suggestions to close skill gaps...'
  ];

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      setInputText(content || '');
    };
    reader.readAsText(file);
  };

  const handleLoadSample = (sample: SampleResume) => {
    setFileName(`${sample.id}.txt`);
    setInputText(sample.rawText);
  };

  const handleStartAnalysis = () => {
    if (!inputText.trim()) return;

    setIsAnalyzing(true);
    setAnalysisStep(0);

    const stepInterval = setInterval(() => {
      setAnalysisStep((prev) => {
        if (prev < analysisSteps.length - 1) {
          return prev + 1;
        } else {
          clearInterval(stepInterval);
          const parsed = parseResumeText(inputText);
          setResults(parsed);
          setIsAnalyzing(false);
          return prev;
        }
      });
    }, 600);
  };

  const handleReset = () => {
    setResults(null);
    setInputText('');
    setFileName(null);
    setIsAnalyzing(false);
    setAnalysisStep(0);
  };

  const handleCopyKeywords = (keywords: string[]) => {
    navigator.clipboard.writeText(keywords.join(', '));
    setCopiedKeywords(true);
    setTimeout(() => setCopiedKeywords(false), 2000);
  };

  const handleExportReport = () => {
    if (!results) return;

    const reportContent = `# CareerIQ AI Resume Intelligence & Career Report
Candidate Name: ${results.candidateName}
Current Inferred Title: ${results.inferredCurrentTitle} (${results.experienceLevel})
ATS Optimization Score: ${results.atsScore}/100

## 1. Top Recommended Career Opportunities
${results.roleMatches.map(r => `### ${r.title} — ${r.adjustedMatchScore}% Match
- Salary Range: ${r.salaryRange} (Avg: ${r.averageSalary})
- Market Growth: ${r.growthRate} (${r.openingsCount})
- Why You Match: ${r.whyYouMatch}
- Verified Skills: ${r.userVerifiedSkills.join(', ')}
- Skill Gaps to Close: ${r.userMissingSkills.join(', ')}
`).join('\n')}

## 2. Targeted Course Suggestions for Skill Development
${results.recommendedCourses.map(c => `### ${c.title}
- Provider: ${c.provider} (${c.instructor})
- Duration: ${c.duration} | Level: ${c.difficulty} | Rating: ${c.rating}/5.0
- Skill Targeted: ${c.skillTarget} (Expected Match Uplift: +${c.matchUplift}%)
- Key Syllabus:
${c.syllabusHighlights.map(s => `  * ${s}`).join('\n')}
`).join('\n')}

## 3. ATS Optimization Recommendations
${results.atsRecommendations.map(rec => `- ${rec}`).join('\n')}

Keywords to Add: ${results.suggestedKeywords.join(', ')}

Generated by CareerIQ Platform • © 2026 CareerIQ AI Inc.
`;

    const blob = new Blob([reportContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${results.candidateName.replace(/\s+/g, '_')}_CareerIQ_Report.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/85 backdrop-blur-2xl flex items-center justify-center p-3 sm:p-6 animate-fadeIn">
      <div className="relative w-full max-w-5xl bg-[#0B1120] border border-white/10 rounded-3xl shadow-2xl shadow-black/95 overflow-hidden flex flex-col max-h-[94vh]">
        
        {/* Glow Header Accent */}
        <div className="absolute -top-px left-12 right-12 h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent" />

        {/* Modal Header */}
        <div className="p-5 sm:p-6 border-b border-white/10 flex items-center justify-between bg-gradient-to-r from-blue-950/40 via-slate-900 to-violet-950/40 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-600 flex items-center justify-center text-white shadow-lg shadow-blue-500/25">
              <Sparkles className="w-5 h-5 text-white animate-pulse" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg sm:text-xl font-bold text-white tracking-tight">
                  AI Resume Intelligence & Course Recommender
                </h3>
                <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400">
                  Neural Scanner
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Extract skills from your resume to unlock verified career opportunities and targeted course suggestions.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/10 transition-colors"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="flex-1 overflow-y-auto p-5 sm:p-7">
          
          {/* VIEW 1: Input / Upload View (When results is null and not analyzing) */}
          {!results && !isAnalyzing && (
            <div className="space-y-6">
              
              {/* Quick Sample Selector Pill Bar */}
              <div className="p-4 rounded-2xl bg-gradient-to-r from-blue-950/30 to-violet-950/30 border border-blue-500/20 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-blue-300 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-blue-400" />
                    Instant 1-Click Test: Pick a sample tech resume
                  </span>
                  <span className="text-[10px] text-slate-400">No upload needed</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                  {SAMPLE_RESUMES.map((sample) => (
                    <button
                      key={sample.id}
                      type="button"
                      onClick={() => handleLoadSample(sample)}
                      className="p-2.5 rounded-xl bg-slate-900/80 hover:bg-slate-800/90 border border-white/10 hover:border-blue-500/30 text-left transition-all group"
                    >
                      <div className="text-xs font-semibold text-white group-hover:text-blue-300 truncate">
                        {sample.title}
                      </div>
                      <div className="text-[10px] text-slate-400 mt-0.5 flex items-center justify-between">
                        <span>{sample.experienceYears}</span>
                        <span className="text-blue-400 group-hover:translate-x-0.5 transition-transform">Use Sample →</span>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Upload Dropzone */}
              <div className="relative border-2 border-dashed border-white/15 hover:border-blue-500/50 rounded-2xl p-6 sm:p-8 text-center transition-all bg-slate-950/40">
                <input
                  type="file"
                  accept=".txt,.pdf,.docx"
                  onChange={handleFileUpload}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                  id="resume-file-input"
                />
                <div className="w-12 h-12 rounded-2xl bg-blue-600/10 border border-blue-500/20 text-blue-400 mx-auto flex items-center justify-center mb-3">
                  <Upload className="w-6 h-6" />
                </div>
                <h4 className="text-sm font-bold text-white">
                  {fileName ? `Loaded: ${fileName}` : 'Drop your resume here, or browse files'}
                </h4>
                <p className="text-xs text-slate-400 mt-1 max-w-sm mx-auto">
                  Supports PDF, Word (.docx), or plain text format. Your data is analyzed locally and securely.
                </p>
                {fileName && (
                  <span className="inline-block mt-2 text-xs font-medium text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1 rounded-full">
                    ✓ Ready to Analyze
                  </span>
                )}
              </div>

              {/* Paste Text Area */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold uppercase tracking-wider text-slate-300">
                    Or Paste Resume Text
                  </label>
                  {inputText && (
                    <button
                      type="button"
                      onClick={() => setInputText('')}
                      className="text-xs text-slate-400 hover:text-rose-400 transition-colors"
                    >
                      Clear Text
                    </button>
                  )}
                </div>
                <textarea
                  rows={6}
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  placeholder="Paste work experience, technical projects, degrees, and skills from your resume..."
                  className="w-full p-4 rounded-xl bg-slate-950 border border-white/10 text-xs font-mono text-slate-200 placeholder-slate-500 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none transition-all leading-relaxed"
                  id="resume-paste-textarea"
                />
              </div>

              {/* Submit Button */}
              <div className="flex items-center justify-end gap-3 pt-2">
                <button
                  type="button"
                  onClick={handleStartAnalysis}
                  disabled={!inputText.trim()}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-8 py-3.5 rounded-xl font-bold text-sm text-white bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 hover:from-blue-500 hover:to-violet-500 shadow-xl shadow-blue-500/25 disabled:opacity-50 disabled:pointer-events-none transition-all"
                  id="analyze-resume-btn"
                >
                  <Sparkles className="w-4 h-4" />
                  <span>Analyze Resume & Recommend Paths</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}

          {/* VIEW 2: Scanning / Telemetry Animation */}
          {isAnalyzing && (
            <div className="py-16 text-center space-y-6 max-w-md mx-auto">
              <div className="relative w-20 h-20 mx-auto">
                <div className="absolute inset-0 rounded-full border-4 border-blue-500/20 animate-ping" />
                <div className="w-20 h-20 rounded-full bg-gradient-to-tr from-blue-600 to-violet-600 flex items-center justify-center text-white shadow-xl shadow-blue-500/40">
                  <Brain className="w-9 h-9 animate-pulse" />
                </div>
              </div>

              <div className="space-y-2">
                <h4 className="text-lg font-bold text-white">
                  Neural Skill Calibration Engine Active
                </h4>
                <p className="text-xs text-blue-400 font-medium animate-pulse">
                  {analysisSteps[analysisStep]}
                </p>
              </div>

              <div className="h-1.5 w-full bg-slate-800 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-blue-500 via-indigo-400 to-violet-500 transition-all duration-500 rounded-full"
                  style={{ width: `${((analysisStep + 1) / analysisSteps.length) * 100}%` }}
                />
              </div>

              <div className="flex items-center justify-center gap-2 text-xs text-slate-400">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>256-bit Secure In-Memory Processing</span>
              </div>
            </div>
          )}

          {/* VIEW 3: Results Dashboard (When results is available) */}
          {results && (
            <div className="space-y-6 animate-fadeIn">
              
              {/* Candidate Overview Card */}
              <div className="p-5 sm:p-6 rounded-2xl bg-gradient-to-r from-blue-950/40 via-slate-900 to-violet-950/40 border border-white/10 flex flex-col md:flex-row items-start md:items-center justify-between gap-5">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-blue-600 to-violet-600 flex items-center justify-center text-white text-lg font-bold shadow-md shadow-blue-500/30">
                    {results.candidateName[0] || 'C'}
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h4 className="text-lg font-bold text-white">{results.candidateName}</h4>
                      <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400">
                        {results.experienceLevel}
                      </span>
                    </div>
                    <p className="text-xs text-slate-400">
                      Inferred: <span className="text-slate-200 font-medium">{results.inferredCurrentTitle}</span> • {results.yearsEstimate} experience
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="text-right">
                    <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">ATS Score</div>
                    <div className="text-lg font-extrabold text-emerald-400">{results.atsScore}/100</div>
                  </div>
                  <button
                    onClick={handleReset}
                    className="px-3 py-1.5 rounded-xl text-xs font-semibold text-slate-300 hover:text-white bg-white/5 hover:bg-white/10 border border-white/10 transition-colors flex items-center gap-1.5"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                    <span>Scan New Resume</span>
                  </button>
                </div>
              </div>

              {/* Extracted Skills Cloud */}
              <div className="p-4 rounded-2xl bg-slate-900/50 border border-white/10 space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    Detected Competencies ({results.extractedSkills.length} identified from resume):
                  </span>
                  <span className="text-slate-500 text-[11px]">Matched across 100+ technical frameworks</span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {results.extractedSkills.map(skill => (
                    <span
                      key={skill}
                      className="px-2.5 py-1 rounded-lg text-xs font-medium bg-blue-500/10 border border-blue-500/20 text-blue-300 flex items-center gap-1"
                    >
                      <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                      <span>{skill}</span>
                    </span>
                  ))}
                </div>
              </div>

              {/* Tab Navigation */}
              <div className="grid grid-cols-3 p-1 rounded-2xl bg-slate-950 border border-white/10">
                <button
                  type="button"
                  onClick={() => setActiveTab('opportunities')}
                  className={`py-2.5 text-xs sm:text-sm font-semibold rounded-xl transition-all flex items-center justify-center gap-2 ${
                    activeTab === 'opportunities'
                      ? 'bg-blue-600 text-white shadow-md shadow-blue-600/30'
                      : 'text-slate-400 hover:text-white'
                  }`}
                  id="tab-opportunities"
                >
                  <Briefcase className="w-4 h-4" />
                  <span>Career Opportunities ({results.roleMatches.length})</span>
                </button>

                <button
                  type="button"
                  onClick={() => setActiveTab('courses')}
                  className={`py-2.5 text-xs sm:text-sm font-semibold rounded-xl transition-all flex items-center justify-center gap-2 ${
                    activeTab === 'courses'
                      ? 'bg-blue-600 text-white shadow-md shadow-blue-600/30'
                      : 'text-slate-400 hover:text-white'
                  }`}
                  id="tab-courses"
                >
                  <BookOpen className="w-4 h-4" />
                  <span>Course Suggestions ({results.recommendedCourses.length})</span>
                </button>

                <button
                  type="button"
                  onClick={() => setActiveTab('ats')}
                  className={`py-2.5 text-xs sm:text-sm font-semibold rounded-xl transition-all flex items-center justify-center gap-2 ${
                    activeTab === 'ats'
                      ? 'bg-blue-600 text-white shadow-md shadow-blue-600/30'
                      : 'text-slate-400 hover:text-white'
                  }`}
                  id="tab-ats"
                >
                  <FileText className="w-4 h-4" />
                  <span>ATS Resume Optimizer</span>
                </button>
              </div>

              {/* TAB 1: Career Opportunities */}
              {activeTab === 'opportunities' && (
                <div className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {results.roleMatches.map((role, idx) => {
                      const isSelected = selectedRoleIndex === idx;
                      return (
                        <div
                          key={role.id}
                          onClick={() => setSelectedRoleIndex(idx)}
                          className={`p-5 rounded-2xl border transition-all cursor-pointer flex flex-col justify-between ${
                            isSelected
                              ? 'bg-[#0F172A] border-blue-500 shadow-xl shadow-blue-500/15 ring-1 ring-blue-500/30'
                              : 'bg-slate-900/60 border-white/10 hover:border-white/20'
                          }`}
                        >
                          <div className="space-y-3">
                            <div className="flex items-start justify-between gap-2">
                              <div>
                                <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                                  {role.category}
                                </span>
                                <h5 className="text-base font-bold text-white mt-0.5">
                                  {role.title}
                                </h5>
                              </div>
                              <div className="text-right shrink-0">
                                <span className="text-sm font-extrabold text-blue-400 bg-blue-500/10 border border-blue-500/20 px-2.5 py-1 rounded-xl">
                                  {role.adjustedMatchScore}% Match
                                </span>
                              </div>
                            </div>

                            <p className="text-xs text-slate-300 leading-relaxed">
                              {role.whyYouMatch}
                            </p>

                            <div className="grid grid-cols-2 gap-2 pt-2 border-t border-white/5 text-xs">
                              <div>
                                <span className="text-[10px] text-slate-400 block">Salary Range</span>
                                <span className="font-bold text-emerald-400">{role.salaryRange}</span>
                              </div>
                              <div>
                                <span className="text-[10px] text-slate-400 block">Growth Trajectory</span>
                                <span className="font-bold text-blue-300">{role.growthRate} ({role.openingsCount})</span>
                              </div>
                            </div>

                            {/* Verified vs Missing Skills */}
                            <div className="space-y-1.5 pt-2">
                              <div className="text-[11px] text-emerald-400 flex items-center gap-1 font-medium">
                                <Check className="w-3.5 h-3.5" />
                                <span>Verified on your resume ({role.userVerifiedSkills.length}):</span>
                              </div>
                              <div className="flex flex-wrap gap-1">
                                {role.userVerifiedSkills.map(s => (
                                  <span key={s} className="text-[10px] px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-300 border border-emerald-500/20">
                                    {s}
                                  </span>
                                ))}
                              </div>

                              {role.userMissingSkills.length > 0 && (
                                <>
                                  <div className="text-[11px] text-amber-400 flex items-center gap-1 font-medium pt-1">
                                    <AlertCircle className="w-3.5 h-3.5" />
                                    <span>High-impact gaps to bridge ({role.userMissingSkills.length}):</span>
                                  </div>
                                  <div className="flex flex-wrap gap-1">
                                    {role.userMissingSkills.map(s => (
                                      <span key={s} className="text-[10px] px-2 py-0.5 rounded bg-amber-500/10 text-amber-300 border border-amber-500/20">
                                        + {s}
                                      </span>
                                    ))}
                                  </div>
                                </>
                              )}
                            </div>
                          </div>

                          <div className="mt-4 pt-3 border-t border-white/5 flex items-center justify-between text-xs text-slate-400">
                            <span>Top Employers: {role.topHiringCompanies.slice(0, 3).join(', ')}</span>
                            <span className="text-blue-400 font-semibold flex items-center gap-1">
                              View Openings <ChevronRight className="w-3.5 h-3.5" />
                            </span>
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Selected Role Sample Openings Banner */}
                  {results.roleMatches[selectedRoleIndex] && (
                    <div className="p-5 rounded-2xl bg-slate-900/80 border border-white/10 space-y-3">
                      <div className="flex items-center justify-between">
                        <h5 className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2">
                          <Briefcase className="w-3.5 h-3.5 text-blue-400" />
                          <span>Live Partner Openings for {results.roleMatches[selectedRoleIndex].title}</span>
                        </h5>
                        <span className="text-xs text-blue-400 font-medium">80+ Verified Referrals</span>
                      </div>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        {results.roleMatches[selectedRoleIndex].sampleOpenings.map((job, jIdx) => (
                          <div key={jIdx} className="p-3.5 rounded-xl bg-slate-950/70 border border-white/5 flex items-center justify-between gap-3">
                            <div>
                              <h6 className="text-xs font-bold text-white">{job.title}</h6>
                              <div className="text-[11px] text-slate-400 mt-0.5">
                                {job.company} • {job.location}
                              </div>
                              <div className="text-[11px] text-emerald-400 font-semibold mt-1">
                                {job.salary} ({job.type})
                              </div>
                            </div>
                            <button
                              onClick={() => {
                                onClose();
                                if (onOpenRoadmap) onOpenRoadmap();
                              }}
                              className="px-3 py-1.5 rounded-lg text-xs font-semibold text-white bg-blue-600 hover:bg-blue-500 shadow-sm shrink-0"
                            >
                              Apply
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* TAB 2: Course Suggestions */}
              {activeTab === 'courses' && (
                <div className="space-y-4">
                  <div className="p-4 rounded-2xl bg-blue-950/30 border border-blue-500/20 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-xl bg-blue-500/20 border border-blue-500/30 flex items-center justify-center text-blue-400">
                        <BookOpen className="w-4 h-4" />
                      </div>
                      <div>
                        <h5 className="text-xs sm:text-sm font-semibold text-white">
                          Curated Skill-Closure Curriculum
                        </h5>
                        <p className="text-[11px] text-slate-400">
                          These courses directly resolve the skill gaps extracted from your resume, raising your career match score up to +18%.
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {results.recommendedCourses.map((course) => (
                      <div
                        key={course.id}
                        className="p-5 rounded-2xl bg-slate-900/70 border border-white/10 hover:border-blue-500/40 transition-all flex flex-col justify-between"
                      >
                        <div className="space-y-3">
                          <div className="flex items-start justify-between gap-2">
                            <div>
                              <span className="text-[10px] font-bold uppercase tracking-wider text-blue-400">
                                {course.provider} • {course.difficulty}
                              </span>
                              <h5 className="text-sm font-bold text-white mt-0.5 leading-snug">
                                {course.title}
                              </h5>
                              <p className="text-[11px] text-slate-400 mt-0.5">
                                Instructor: {course.instructor}
                              </p>
                            </div>
                            <span className="text-xs font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1 rounded-xl shrink-0">
                              +{course.matchUplift}% Match
                            </span>
                          </div>

                          <div className="flex items-center gap-4 text-xs text-slate-300">
                            <span className="flex items-center gap-1 text-amber-400 font-semibold">
                              <Star className="w-3.5 h-3.5 fill-current" /> {course.rating}
                            </span>
                            <span className="text-slate-500">•</span>
                            <span>{course.duration}</span>
                            <span className="text-slate-500">•</span>
                            <span className="text-slate-400">{course.reviewsCount}</span>
                          </div>

                          <div className="space-y-1.5 pt-2 border-t border-white/5">
                            <span className="text-[11px] font-semibold text-slate-300 block">
                              Syllabus Highlights:
                            </span>
                            <ul className="space-y-1">
                              {course.syllabusHighlights.map((hl, i) => (
                                <li key={i} className="text-[11px] text-slate-400 flex items-start gap-1.5">
                                  <span className="text-blue-400 shrink-0">•</span>
                                  <span>{hl}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        </div>

                        <div className="mt-4 pt-3 border-t border-white/5 flex items-center justify-between gap-2">
                          <span className="text-[11px] text-slate-400">
                            Target: <span className="text-white font-medium">{course.skillTarget}</span>
                          </span>
                          <a
                            href={course.url}
                            target="_blank"
                            rel="noreferrer"
                            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-white bg-blue-600 hover:bg-blue-500 transition-all shadow-md"
                          >
                            <span>Enroll Course</span>
                            <ExternalLink className="w-3 h-3" />
                          </a>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* TAB 3: ATS Resume Optimizer */}
              {activeTab === 'ats' && (
                <div className="space-y-4">
                  {/* ATS Score card */}
                  <div className="p-5 rounded-2xl bg-slate-900/80 border border-white/10 flex flex-col sm:flex-row items-center justify-between gap-4">
                    <div>
                      <h5 className="text-sm font-bold text-white flex items-center gap-2">
                        <span>ATS Parser Readability Score</span>
                        <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                          Interview Ready
                        </span>
                      </h5>
                      <p className="text-xs text-slate-400 mt-1">
                        How cleanly automated recruiter scanning engines parse your credentials and quantify business value.
                      </p>
                    </div>
                    <div className="text-center sm:text-right">
                      <div className="text-3xl font-black text-emerald-400">{results.atsScore} / 100</div>
                      <span className="text-[10px] text-slate-400">Target Benchmark: 85+</span>
                    </div>
                  </div>

                  {/* Keywords to add */}
                  <div className="p-5 rounded-2xl bg-slate-900/60 border border-white/10 space-y-3">
                    <div className="flex items-center justify-between">
                      <h5 className="text-xs font-bold uppercase tracking-wider text-slate-300">
                        High-Demand Keywords to Embed in Your Summary & Bullets
                      </h5>
                      <button
                        type="button"
                        onClick={() => handleCopyKeywords(results.suggestedKeywords)}
                        className="text-xs font-semibold text-blue-400 hover:text-blue-300 flex items-center gap-1"
                      >
                        {copiedKeywords ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        <span>{copiedKeywords ? 'Copied to Clipboard!' : 'Copy Keywords'}</span>
                      </button>
                    </div>

                    <div className="flex flex-wrap gap-2">
                      {results.suggestedKeywords.map(kw => (
                        <span
                          key={kw}
                          className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-violet-500/10 border border-violet-500/25 text-violet-300 flex items-center gap-1.5"
                        >
                          <span>+ {kw}</span>
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Bullet Point Optimization Guidance */}
                  <div className="p-5 rounded-2xl bg-slate-900/60 border border-white/10 space-y-3">
                    <h5 className="text-xs font-bold uppercase tracking-wider text-slate-300">
                      Actionable Bullet-Point Improvements
                    </h5>
                    <ul className="space-y-2.5">
                      {results.atsRecommendations.map((rec, rIdx) => (
                        <li key={rIdx} className="p-3 rounded-xl bg-slate-950/60 border border-white/5 text-xs text-slate-300 flex items-start gap-2.5">
                          <CheckCircle2 className="w-4 h-4 text-blue-400 shrink-0 mt-0.5" />
                          <span className="leading-relaxed">{rec}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

            </div>
          )}

        </div>

        {/* Modal Footer Controls */}
        <div className="p-4 sm:p-6 border-t border-white/10 bg-[#070B14] flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0">
          <div className="flex items-center gap-2 text-xs text-slate-400">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>AI Career & Course Guidance • 100% Confidential</span>
          </div>

          <div className="flex items-center gap-2.5 w-full sm:w-auto">
            {results && (
              <button
                type="button"
                onClick={handleExportReport}
                className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-200 hover:text-white bg-white/5 hover:bg-white/10 border border-white/10 transition-colors"
                id="export-resume-report-btn"
              >
                <Download className="w-4 h-4 text-blue-400" />
                <span>{downloadSuccess ? 'Report Exported!' : 'Export Career Report (.md)'}</span>
              </button>
            )}

            <button
              type="button"
              onClick={onClose}
              className="w-full sm:w-auto px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-300 hover:text-white border border-white/10 hover:bg-white/5 transition-colors"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
