import React, { useState } from 'react';
import { 
  X, 
  Upload, 
  Sparkles, 
  AlertCircle, 
  ArrowRight, 
  Download, 
  Check, 
  Brain,
  ShieldCheck,
  ChevronRight
} from 'lucide-react';
import { SAMPLE_RESUMES, SampleResume } from '../../data/resumeData';
import { parseResumeText, ParsedResumeResult } from '../../utils/resumeParser';

interface ResumeScannerModalProps {
  isOpen: boolean;
  onClose: () => void;
  onOpenRoadmap?: () => void;
}

export const ResumeScannerModal: React.FC<ResumeScannerModalProps> = ({ 
  isOpen, 
  onClose,
  onOpenRoadmap 
}) => {
  const [inputText, setInputText] = useState('');
  const [fileName, setFileName] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisStep, setAnalysisStep] = useState(0);
  const [results, setResults] = useState<ParsedResumeResult | null>(null);

  const [downloadSuccess, setDownloadSuccess] = useState(false);
  const [selectedRoleIndex, setSelectedRoleIndex] = useState(0);

  if (!isOpen) return null;

  const analysisSteps = [
    'Ingesting document & parsing structural text blocks...',
    'Extracting technical competencies, tools & leadership history...',
    'Calibrating neural match scores across 12,000+ live market roles...',
    'Synthesizing personalized course suggestions to close skill gaps...'
  ];

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      setInputText(content || '');
    };
    reader.readAsText(file);
  };

  const handleLoadSample = (sample: SampleResume) => {
    setFileName(`${sample.id}.txt`);
    setInputText(sample.rawText);
  };

  const handleStartAnalysis = () => {
    if (!inputText.trim()) return;

    setIsAnalyzing(true);
    setAnalysisStep(0);

    const stepInterval = setInterval(() => {
      setAnalysisStep((prev) => {
        if (prev < analysisSteps.length - 1) {
          return prev + 1;
        } else {
          clearInterval(stepInterval);
          const parsed = parseResumeText(inputText);
          setResults(parsed);
          setIsAnalyzing(false);
          return prev;
        }
      });
    }, 600);
  };

  const handleReset = () => {
    setResults(null);
    setInputText('');
    setFileName(null);
    setIsAnalyzing(false);
    setAnalysisStep(0);
  };


  const handleExportReport = () => {
    if (!results) return;

    const reportContent = `# CareerIQ AI Resume Intelligence & Career Report
Candidate Name: ${results.candidateName}
Current Inferred Title: ${results.inferredCurrentTitle} (${results.experienceLevel})
ATS Optimization Score: ${results.atsScore}/100

## 1. Top Recommended Career Opportunities
${results.roleMatches.map(r => `### ${r.title} — ${r.adjustedMatchScore}% Match
- Salary Range: ${r.salaryRange} (Avg: ${r.averageSalary})
- Market Growth: ${r.growthRate} (${r.openingsCount})
- Why You Match: ${r.whyYouMatch}
- Verified Skills: ${r.userVerifiedSkills.join(', ')}
- Skill Gaps to Close: ${r.userMissingSkills.join(', ')}
`).join('\n')}

## 2. Targeted Course Suggestions for Skill Development
${results.recommendedCourses.map(c => `### ${c.title}
- Provider: ${c.provider} (${c.instructor})
- Duration: ${c.duration} | Level: ${c.difficulty} | Rating: ${c.rating}/5.0
- Skill Targeted: ${c.skillTarget} (Expected Match Uplift: +${c.matchUplift}%)
- Key Syllabus:
${c.syllabusHighlights.map(s => `  * ${s}`).join('\n')}
`).join('\n')}

## 3. ATS Optimization Recommendations
${results.atsRecommendations.map(rec => `- ${rec}`).join('\n')}

Keywords to Add: ${results.suggestedKeywords.join(', ')}

Generated by CareerIQ Platform • © 2026 CareerIQ AI Inc.
`;

    const blob = new Blob([reportContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${results.candidateName.replace(/\s+/g, '_')}_CareerIQ_Report.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/85 backdrop-blur-2xl flex items-center justify-center p-3 sm:p-6 animate-fadeIn">
      <div className="relative w-full max-w-5xl bg-[#0B1120] border border-white/10 rounded-3xl shadow-2xl shadow-black/95 overflow-hidden flex flex-col max-h-[94vh]">
        
        {/* Glow Header Accent */}
        <div className="absolute -top-px left-12 right-12 h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent" />

        {/* Modal Header */}
        <div className="p-5 sm:p-6 border-b border-white/10 flex items-center justify-between bg-gradient-to-r from-blue-950/40 via-slate-900 to-violet-950/40 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-600 flex items-center justify-center text-white shadow-lg shadow-blue-500/25">
              <Sparkles className="w-5 h-5 text-white animate-pulse" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg sm:text-xl font-bold text-white tracking-tight">
                  AI Resume Intelligence & Course Recommender
                </h3>
                <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400">
                  Neural Scanner
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Extract skills from your resume to unlock verified career opportunities and targeted course suggestions.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/10 transition-colors"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="flex-1 overflow-y-auto p-5 sm:p-7">
          
          {/* VIEW 1: Input / Upload View (When results is null and not analyzing) */}
          {!results && !isAnalyzing && (
            <div className="space-y-6">
              
              {/* Quick Sample Selector Pill Bar */}
              <div className="p-4 rounded-2xl bg-gradient-to-r from-blue-950/30 to-violet-950/30 border border-blue-500/20 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-blue-300 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-blue-400" />
                    Instant 1-Click Test: Pick a sample tech resume
                  </span>
                  <span className="text-[10px] text-slate-400">No upload needed</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                  {SAMPLE_RESUMES.map((sample) => (
                    <button
                      key={sample.id}
                      type="button"
                      onClick={() => handleLoadSample(sample)}
                      className="p-2.5 rounded-xl bg-slate-900/80 hover:bg-slate-800/90 border border-white/10 hover:border-blue-500/30 text-left transition-all group"
                    >
                      <div className="text-xs font-semibold text-white group-hover:text-blue-300 truncate">
                        {sample.title}
                      </div>
                      <div className="text-[10px] text-slate-400 mt-0.5 flex items-center justify-between">
                        <span>{sample.experienceYears}</span>
                        <span className="text-blue-400 group-hover:translate-x-0.5 transition-transform">Use Sample →</span>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Upload Dropzone */}
              <div className="relative border-2 border-dashed border-white/15 hover:border-blue-500/50 rounded-2xl p-6 sm:p-8 text-center transition-all bg-slate-950/40">
                <input
                  type="file"
                  accept=".txt,.pdf,.docx"
                  onChange={handleFileUpload}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                  id="resume-file-input"
                />
                <div className="w-12 h-12 rounded-2xl bg-blue-600/10 border border-blue-500/20 text-blue-400 mx-auto flex items-center justify-center mb-3">
                  <Upload className="w-6 h-6" />
                </div>
                <h4 className="text-sm font-bold text-white">
                  {fileName ? `Loaded: ${fileName}` : 'Drop your resume here, or browse files'}
                </h4>
                <p className="text-xs text-slate-400 mt-1 max-w-sm mx-auto">
                  Supports PDF, Word (.docx), or plain text format. Your data is analyzed locally and securely.
                </p>
                {fileName && (
                  <span className="inline-block mt-2 text-xs font-medium text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1 rounded-full">
                    ✓ Ready to Analyze
                  </span>
                )}
              </div>

              {/* Paste Text Area */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold uppercase tracking-wider text-slate-300">
                    Or Paste Resume Text
                  </label>
                  {inputText && (
                    <button
                      type="button"
                      onClick={() => setInputText('')}
                      className="text-xs text-slate-400 hover:text-rose-400 transition-colors"
                    >
                      Clear Text
                    </button>
                  )}
                </div>
                <textarea
                  rows={6}
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  placeholder="Paste work experience, technical projects, degrees, and skills from your resume..."
                  className="w-full p-4 rounded-xl bg-slate-950 border border-white/10 text-xs font-mono text-slate-200 placeholder-slate-500 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none transition-all leading-relaxed"
                  id="resume-paste-textarea"
                />
              </div>

              {/* Submit Button */}
              <div className="flex items-center justify-end gap-3 pt-2">
                <button
                  type="button"
                  onClick={handleStartAnalysis}
                  disabled={!inputText.trim()}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-8 py-3.5 rounded-xl font-bold text-sm text-white bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 hover:from-blue-500 hover:to-violet-500 shadow-xl shadow-blue-500/25 disabled:opacity-50 disabled:pointer-events-none transition-all"
                  id="analyze-resume-btn"
                >
                  <Sparkles className="w-4 h-4" />
                  <span>Analyze Resume & Recommend Paths</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}

          {/* VIEW 2: Scanning / Telemetry Animation */}
          {isAnalyzing && (
            <div className="py-16 text-center space-y-6 max-w-md mx-auto">
              <div className="relative w-20 h-20 mx-auto">
                <div className="absolute inset-0 rounded-full border-4 border-blue-500/20 animate-ping" />
                <div className="w-20 h-20 rounded-full bg-gradient-to-tr from-blue-600 to-violet-600 flex items-center justify-center text-white shadow-xl shadow-blue-500/40">
                  <Brain className="w-9 h-9 animate-pulse" />
                </div>
              </div>

              <div className="space-y-2">
                <h4 className="text-lg font-bold text-white">
                  Neural Skill Calibration Engine Active
                </h4>
                <p className="text-xs text-blue-400 font-medium animate-pulse">
                  {analysisSteps[analysisStep]}
                </p>
              </div>

              <div className="h-1.5 w-full bg-slate-800 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-blue-500 via-indigo-400 to-violet-500 transition-all duration-500 rounded-full"
                  style={{ width: `${((analysisStep + 1) / analysisSteps.length) * 100}%` }}
                />
              </div>

              <div className="flex items-center justify-center gap-2 text-xs text-slate-400">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>256-bit Secure In-Memory Processing</span>
              </div>
            </div>
          )}

          {/* VIEW 3: Results Dashboard (When results is available) */}
          {results && (
            <div className="space-y-5 animate-fadeIn">
              
              {/* Career Opportunity Cards — Direct 2×2 Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {results.roleMatches.map((role, idx) => {
                  const isSelected = selectedRoleIndex === idx;
                  const isHighMatch = role.adjustedMatchScore >= 75;
                  const matchBadgeBg = isHighMatch 
                    ? 'bg-emerald-500/10 border-emerald-500/25 text-emerald-400' 
                    : 'bg-blue-500/10 border-blue-500/20 text-blue-400';
                  return (
                    <div
                      key={role.id}
                      onClick={() => setSelectedRoleIndex(idx)}
                      className={`p-5 rounded-2xl border transition-all cursor-pointer flex flex-col justify-between ${
                        isSelected
                          ? 'bg-[#0F172A] border-blue-500 shadow-xl shadow-blue-500/15 ring-1 ring-blue-500/30'
                          : 'bg-slate-900/60 border-white/10 hover:border-white/20'
                      }`}
                    >
                      <div className="space-y-3">
                        {/* Category + Title + Match Badge */}
                        <div className="flex items-start justify-between gap-2">
                          <div>
                            <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                              {role.category}
                            </span>
                            <h5 className="text-base font-bold text-white mt-0.5 leading-snug">
                              {role.title}
                            </h5>
                          </div>
                          <div className="text-right shrink-0">
                            <span className={`text-sm font-extrabold px-2.5 py-1 rounded-xl border ${matchBadgeBg}`}>
                              {role.adjustedMatchScore}% Match
                            </span>
                          </div>
                        </div>

                        {/* Description */}
                        <p className="text-xs text-slate-300 leading-relaxed">
                          {role.whyYouMatch}
                        </p>

                        {/* Salary + Growth */}
                        <div className="grid grid-cols-2 gap-2 pt-2 border-t border-white/5 text-xs">
                          <div>
                            <span className="text-[10px] text-slate-400 block">Salary Range</span>
                            <span className="font-bold text-emerald-400">{role.salaryRange}</span>
                          </div>
                          <div>
                            <span className="text-[10px] text-slate-400 block">Growth Trajectory</span>
                            <span className="font-bold text-blue-300">{role.growthRate} ({role.openingsCount})</span>
                          </div>
                        </div>

                        {/* Verified vs Missing Skills */}
                        <div className="space-y-1.5 pt-2">
                          <div className="text-[11px] text-emerald-400 flex items-center gap-1 font-medium">
                            <Check className="w-3.5 h-3.5" />
                            <span>Verified on your resume ({role.userVerifiedSkills.length}):</span>
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {role.userVerifiedSkills.map(s => (
                              <span key={s} className="text-[10px] px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-300 border border-emerald-500/20">
                                {s}
                              </span>
                            ))}
                          </div>

                          {role.userMissingSkills.length > 0 && (
                            <>
                              <div className="text-[11px] text-amber-400 flex items-center gap-1 font-medium pt-1">
                                <AlertCircle className="w-3.5 h-3.5" />
                                <span>High-impact gaps to bridge ({role.userMissingSkills.length}):</span>
                              </div>
                              <div className="flex flex-wrap gap-1">
                                {role.userMissingSkills.map(s => (
                                  <span key={s} className="text-[10px] px-2 py-0.5 rounded bg-amber-500/10 text-amber-300 border border-amber-500/20">
                                    + {s}
                                  </span>
                                ))}
                              </div>
                            </>
                          )}
                        </div>
                      </div>

                      {/* Footer: Top Employers + View Openings */}
                      <div className="mt-4 pt-3 border-t border-white/5 flex items-center justify-between text-xs text-slate-400">
                        <span>Top Employers: {role.topHiringCompanies.slice(0, 3).join(', ')}</span>
                        <span className="text-blue-400 font-semibold flex items-center gap-1">
                          View Openings <ChevronRight className="w-3.5 h-3.5" />
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>

            </div>
          )}

        </div>

        {/* Modal Footer Controls */}
        <div className="p-4 sm:p-6 border-t border-white/10 bg-[#070B14] flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0">
          <div className="flex items-center gap-2 text-xs text-slate-400">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>AI Career & Course Guidance • 100% Confidential</span>
          </div>

          <div className="flex items-center gap-2.5 w-full sm:w-auto">
            {results && (
              <button
                type="button"
                onClick={handleExportReport}
                className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-200 hover:text-white bg-white/5 hover:bg-white/10 border border-white/10 transition-colors"
                id="export-resume-report-btn"
              >
                <Download className="w-4 h-4 text-blue-400" />
                <span>{downloadSuccess ? 'Report Exported!' : 'Export Career Report (.md)'}</span>
              </button>
            )}

            <button
              type="button"
              onClick={onClose}
              className="w-full sm:w-auto px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-300 hover:text-white border border-white/10 hover:bg-white/5 transition-colors"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
